// Package prompts holds the byte-verbatim Go ports of every LLM prompt builder
// in assay's Python source of truth: the reasoner system/task prompts in
// reasoners/harnesses.py, the merge-gate classification prompt in merge_gate.py,
// the polish prompt in polish.py, and the coverage-gap review prompt in
// orchestrator.py.
//
// Each builder renders output that is byte-identical to the Python f-string /
// str-concat builder for the same inputs, including:
//   - Python str()/repr() formatting of interpolated lists (e.g. the compound
//     dedup `Tags: ['a', 'b']` single-quoted list repr),
//   - f-string float formatting (str(float) and `{x:.2f}`),
//   - json.dumps(..., default=str) context blocks (insertion-ordered keys,
//     ", "/": " separators, ensure_ascii escaping) via the pyjson encoder, and
//   - Python truthiness for the optional prompt sections.
//
// The reasoner packages (T3.1) and the gates package (T3.2) import these
// builders instead of embedding prompt strings, so there is exactly one copy of
// each prompt and the golden tests (testdata/*.txt, generated by
// scripts/gen_golden.py from the real Python builders) pin it byte-for-byte.
package prompts

import (
	"math"
	"path"
	"reflect"
	"strconv"
	"strings"
)

// contextPath renders repository-relative context references with Python's
// slash separator on every host. These paths are prompt text, not filesystem
// operations; writers still use filepath.Join at their call sites.
func contextPath(repoPath string, elems ...string) string {
	parts := append([]string{strings.ReplaceAll(repoPath, "\\", "/")}, elems...)
	return path.Join(parts...)
}

// ---------------------------------------------------------------------------
// Python-parity scalar/list formatting.
//
// The Python builders interpolate values directly into f-strings, which uses
// Python's str()/repr() rendering. These helpers reproduce that rendering so
// the Go output is byte-identical.
// ---------------------------------------------------------------------------

// pyStr reproduces Python str(v) for the scalar kinds interpolated into the
// f-string builders.
func pyStr(v any) string {
	switch x := v.(type) {
	case nil:
		return "None"
	case string:
		return x
	case bool:
		if x {
			return "True"
		}
		return "False"
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return pyFloat(x)
	case float32:
		return pyFloat(float64(x))
	default:
		return pyRepr(v)
	}
}

// pyRepr reproduces Python repr(v) for the value kinds these prompts repr:
// strings (single-quoted), bools, numbers, and lists (elements repr'd). This is
// what `{some_list}` interpolation produces (e.g. compound-dedup Tags).
func pyRepr(v any) string {
	switch x := v.(type) {
	case nil:
		return "None"
	case string:
		return pyReprString(x)
	case bool:
		if x {
			return "True"
		}
		return "False"
	case int:
		return strconv.Itoa(x)
	case int64:
		return strconv.FormatInt(x, 10)
	case float64:
		return pyFloat(x)
	case float32:
		return pyFloat(float64(x))
	}
	rv := reflect.ValueOf(v)
	switch rv.Kind() {
	case reflect.Slice, reflect.Array:
		parts := make([]string, rv.Len())
		for i := 0; i < rv.Len(); i++ {
			parts[i] = pyRepr(rv.Index(i).Interface())
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case reflect.Ptr:
		if rv.IsNil() {
			return "None"
		}
		return pyRepr(rv.Elem().Interface())
	}
	return pyStr(v)
}

// pyReprString reproduces Python's repr() of a string: single quotes by default,
// double quotes when the string contains a single quote but no double quote,
// with backslash, the active quote, and the common control characters escaped.
func pyReprString(s string) string {
	quote := byte('\'')
	if strings.Contains(s, "'") && !strings.Contains(s, "\"") {
		quote = '"'
	}
	var b strings.Builder
	b.WriteByte(quote)
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case rune(quote):
			b.WriteByte('\\')
			b.WriteRune(r)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte(quote)
	return b.String()
}

// pyFloat reproduces Python's repr()/str() of a float (identical for finite
// floats since Python 3.1): the shortest decimal that round-trips, always
// carrying a decimal point or exponent so it reads as a float. This is also
// what json.dumps emits for a float. Integral values print with a trailing
// ".0" (Python repr(100.0) == "100.0").
func pyFloat(f float64) string {
	if math.IsInf(f, 1) {
		return "inf"
	}
	if math.IsInf(f, -1) {
		return "-inf"
	}
	if math.IsNaN(f) {
		return "nan"
	}
	s := strconv.FormatFloat(f, 'g', -1, 64)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s
}

// pyDotTwoF reproduces Python `f"{x:.2f}"` — fixed two decimals, round-half-to-
// even (Go's strconv 'f' and Python's format spec agree on banker's rounding).
func pyDotTwoF(f float64) string {
	return strconv.FormatFloat(f, 'f', 2, 64)
}

// runeSlice reproduces Python's s[:n] slice, which counts Unicode code points,
// not bytes.
func runeSlice(s string, n int) string {
	if n < 0 {
		n = 0
	}
	runes := []rune(s)
	if len(runes) <= n {
		return s
	}
	return string(runes[:n])
}

// delimitPRDescription wraps author-controlled text in tags that cannot occur
// in the text. It mirrors _delimit_pr_description in the Python node.
func delimitPRDescription(description string) string {
	if description == "" {
		return ""
	}

	delimiter := "PR_AF_AUTHOR_DESCRIPTION"
	for strings.Contains(description, delimiter) {
		delimiter += "_"
	}
	return "<" + delimiter + ">\n" + description + "\n</" + delimiter + ">"
}

// firstN returns xs[:n] (Python list slice), safe when len(xs) <= n.
func firstN[T any](xs []T, n int) []T {
	if len(xs) <= n {
		return xs
	}
	return xs[:n]
}

// joinComma reproduces ", ".join(list) for a []string.
func joinComma(xs []string) string {
	return strings.Join(xs, ", ")
}

// orNilSlice reproduces Python's `x or []`: nil for an empty/absent list.
func orEmpty(xs []string) []string {
	if xs == nil {
		return []string{}
	}
	return xs
}
