package orch

// V11: the summary Markdown is byte-identical to the real Python formatter for a
// fixed fixture (testdata/summary_golden.txt, generated by gen_summary_golden.py
// via the venv). V2: ReviewResult marshals with exactly Python's model_dump() key
// set at every level (testdata/result_keys.json, generated by gen_result_keys.py).

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/strich/assay/internal/config"
	"github.com/strich/assay/internal/github"
	"github.com/strich/assay/internal/schemas"
)

func fixedClockOrch(t *testing.T) *Orchestrator {
	t.Helper()
	o := New(Deps{LLM: &fakeLLM{}}, schemas.ReviewInput{}, config.DefaultReviewConfig())
	o.reviewID = "rev_abc123def456"
	o.clock = func() time.Duration { return 12300 * time.Millisecond }
	o.crossRefCount = 1
	o.adversaryConfirmedCount = 2
	o.adversaryChallengedCount = 1
	o.coverageIterations = 1
	o.agentInvocations = 7
	o.metaSelectorResults = []schemas.MetaDimensionResult{
		{Lens: "semantic", Dimensions: []schemas.ReviewDimension{{ID: "s1", Name: "A"}, {ID: "s2", Name: "B"}}, Confidence: 0.8},
		{Lens: "mechanical", Dimensions: []schemas.ReviewDimension{{ID: "m1", Name: "C"}}, Confidence: 0.6},
	}
	return o
}

type ownPRFallbackGH struct {
	reviews []schemas.GitHubReview
}

func (g *ownPRFallbackGH) ParsePRURL(string) (string, string, int, error) {
	return "", "", 0, nil
}

func (g *ownPRFallbackGH) FetchPR(context.Context, string, string, int) (schemas.GitHubPRData, error) {
	return schemas.GitHubPRData{}, nil
}

func (g *ownPRFallbackGH) PostReview(_ context.Context, _ string, _ string, _ int, review schemas.GitHubReview, _ string) (map[string]any, error) {
	g.reviews = append(g.reviews, review)
	if len(g.reviews) == 1 {
		return nil, &github.APIError{StatusCode: 422, Body: "review cannot be submitted on your own pull request"}
	}
	return map[string]any{"id": 42}, nil
}

func TestPostReview_OwnPR422FallsBackToComment(t *testing.T) {
	gh := &ownPRFallbackGH{}
	o := New(Deps{LLM: &fakeLLM{}, GH: gh}, schemas.ReviewInput{}, config.DefaultReviewConfig())
	o.prData = &schemas.GitHubPRData{Owner: "o", Repo: "r", Number: 7, HeadSHA: "sha"}
	comments := []schemas.GitHubComment{{Path: "a.go", Line: 3, Body: "comment"}}

	o.postReview(context.Background(), schemas.GitHubReview{Body: "initial", Event: "REQUEST_CHANGES"}, "fallback", comments)

	if len(gh.reviews) != 2 {
		t.Fatalf("PostReview calls = %d, want 2", len(gh.reviews))
	}
	if gh.reviews[0].Event != "REQUEST_CHANGES" {
		t.Errorf("initial event = %q, want REQUEST_CHANGES", gh.reviews[0].Event)
	}
	if got := gh.reviews[1]; got.Event != "COMMENT" || got.Body != "fallback" || !equalComments(got.Comments, comments) {
		t.Errorf("fallback review = %#v, want COMMENT with fallback body and comments", got)
	}
}

func equalComments(a, b []schemas.GitHubComment) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func TestSummaryGoldenByteExact(t *testing.T) {
	o := fixedClockOrch(t)
	findings := []schemas.ScoredFinding{
		{
			ID: "f_000", DimensionID: "d1", DimensionName: "Security",
			FilePath: "src/a.py", LineStart: 10, LineEnd: 10, DiffSide: "RIGHT",
			Severity: "critical", Title: "Null dereference",
			Body: "The value can be None. Handle it before use.", Confidence: 0.9,
			Blocking: true, BlockingReason: "Crashes on null input.",
		},
		{
			ID: "f_001", DimensionID: "d2", DimensionName: "Performance",
			FilePath: "src/b.py", LineStart: 20, LineEnd: 25, DiffSide: "RIGHT",
			Severity: "important", Title: "Quadratic loop",
			Body: "This nested loop is O(n^2) and will not scale.", Confidence: 0.7,
		},
		{
			ID: "f_002", DimensionID: "d3", DimensionName: "Style",
			FilePath: "", LineStart: 0, LineEnd: 0, DiffSide: "RIGHT",
			Severity: "nitpick", Title: "Typo in comment",
			Body: "Fix the spelling.", Confidence: 0.5,
		},
	}
	intake := schemas.IntakeResult{
		PrType: "feature", Complexity: "standard",
		Languages: []string{"python"}, AreasTouched: []string{"api"}, RiskSignals: []string{},
		AIGenerated: 0.1, ReviewDepth: "standard", PrSummary: "Adds a caching layer to the API.",
	}
	plan := schemas.ReviewPlan{
		Dimensions: []schemas.ReviewDimension{
			{ID: "sec", Name: "Security", TargetFiles: []string{"src/a.py"}},
			{ID: "perf", Name: "Performance", TargetFiles: []string{"src/b.py", "src/c.py"}},
		},
		CrossRefHints: []string{},
	}

	got := o.formatSummary(findings, "REQUEST_CHANGES", &intake, &plan)

	want, err := os.ReadFile(filepath.Join("testdata", "summary_golden.txt"))
	if err != nil {
		t.Fatal(err)
	}
	wantSummary := strings.ReplaceAll(string(want), "\r\n", "\n")
	if got != wantSummary {
		reportFirstDiff(t, wantSummary, got)
	}
}

// reportFirstDiff surfaces the first differing byte with a small window.
func reportFirstDiff(t *testing.T, want, got string) {
	t.Helper()
	n := len(want)
	if len(got) < n {
		n = len(got)
	}
	for i := 0; i < n; i++ {
		if want[i] != got[i] {
			lo := i - 40
			if lo < 0 {
				lo = 0
			}
			hiW := i + 40
			if hiW > len(want) {
				hiW = len(want)
			}
			hiG := i + 40
			if hiG > len(got) {
				hiG = len(got)
			}
			t.Fatalf("summary differs at byte %d\n want …%q…\n  got …%q…", i, want[lo:hiW], got[lo:hiG])
		}
	}
	if len(want) != len(got) {
		t.Fatalf("summary length differs: want %d bytes, got %d bytes\ngot tail: %q", len(want), len(got), got[n:])
	}
}

func TestReviewResultKeySetParity(t *testing.T) {
	llm := &fakeLLM{}
	cfg := config.DefaultReviewConfig()
	in := schemas.ReviewInput{PrURL: strPtr("https://github.com/o/r/pull/1"), DryRun: true}
	o := New(Deps{LLM: llm}, in, cfg)
	o.prData = &schemas.GitHubPRData{
		Owner: "o", Repo: "r", Number: 1,
		ChangedFiles: []schemas.ChangedFile{{Path: "src/a.py", Patch: "@@ -1,1 +1,5 @@\n+x"}},
	}

	scored := []schemas.ScoredFinding{{
		ID: "f_000", DimensionID: "d1", DimensionName: "Dim",
		FilePath: "src/a.py", LineStart: 1, LineEnd: 1, DiffSide: "RIGHT",
		Severity: "important", Title: "t", Body: "b", Confidence: 0.5,
	}}
	intake := schemas.IntakeResult{
		PrType: "feature", Complexity: "standard",
		Languages: []string{}, AreasTouched: []string{}, RiskSignals: []string{},
		AIGenerated: 0.0, ReviewDepth: "standard", PrSummary: "s",
	}
	anatomy := schemas.AnatomyResult{
		Files: []schemas.FileChange{}, Clusters: []schemas.ChangeCluster{},
		BlastRadius: []string{}, DependencyGraph: map[string][]string{},
		RiskSurfaces: []string{}, UnrelatedChanges: []string{}, IntentGaps: []string{},
	}
	plan := schemas.ReviewPlan{Dimensions: []schemas.ReviewDimension{}, CrossRefHints: []string{}, TotalBudget: defaultBudgetAllocation()}

	result, err := o.generateOutput(context.Background(), scored, intake, anatomy, plan, true)
	if err != nil {
		t.Fatal(err)
	}

	b, err := json.Marshal(result)
	if err != nil {
		t.Fatal(err)
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		t.Fatal(err)
	}

	expected := loadExpectedKeys(t)

	assertKeys(t, "result", m, expected["result"])
	review := m["review"].(map[string]any)
	assertKeys(t, "review", review, expected["review"])
	comments := review["comments"].([]any)
	if len(comments) == 0 {
		t.Fatal("expected at least one comment for the key-set check")
	}
	assertKeys(t, "comment", comments[0].(map[string]any), expected["comment"])
	findings := m["findings"].([]any)
	assertKeys(t, "finding", findings[0].(map[string]any), expected["finding"])
	assertKeys(t, "summary", m["summary"].(map[string]any), expected["summary"])
	meta := m["metadata"].(map[string]any)
	assertKeys(t, "metadata", meta, expected["metadata"])
	assertKeys(t, "intake", meta["intake"].(map[string]any), expected["intake"])
	assertKeys(t, "anatomy", meta["anatomy"].(map[string]any), expected["anatomy"])
	assertKeys(t, "plan", meta["plan"].(map[string]any), expected["plan"])
	assertKeys(t, "budget", meta["budget"].(map[string]any), expected["budget"])
}

func loadExpectedKeys(t *testing.T) map[string][]string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", "result_keys.json"))
	if err != nil {
		t.Fatal(err)
	}
	var expected map[string][]string
	if err := json.Unmarshal(b, &expected); err != nil {
		t.Fatal(err)
	}
	return expected
}

func assertKeys(t *testing.T, level string, obj map[string]any, want []string) {
	t.Helper()
	got := make([]string, 0, len(obj))
	for k := range obj {
		got = append(got, k)
	}
	sort.Strings(got)
	sort.Strings(want)
	if len(got) != len(want) {
		t.Errorf("%s: key count mismatch\n got %v\nwant %v", level, got, want)
		return
	}
	for i := range got {
		if got[i] != want[i] {
			t.Errorf("%s: key set mismatch\n got %v\nwant %v", level, got, want)
			return
		}
	}
}
