package reasoners

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/strich/assay/internal/prompts"
	"github.com/strich/assay/internal/schemas"
)

// Golden values in this file were captured from the real Python helpers:
//
//	PYTHONPATH=src <praf-venv>/bin/python — importing
//	pr_af.reasoners.harnesses._auto_depth / _language_from_path /
//	_extract_languages / _extract_areas / _risk_signals /
//	_ai_generated_confidence / _pr_summary over the fixturePR() inputs.

// Contract: _auto_depth mapping with "standard" as the default.
func TestAutoDepthGolden(t *testing.T) {
	cases := map[string]string{
		"trivial":  "quick",
		"standard": "standard",
		"complex":  "deep",
		"massive":  "deep",
		"":         "standard",
		"weird":    "standard",
		"quick":    "standard",
	}
	for in, want := range cases {
		if got := autoDepth(in); got != want {
			t.Errorf("autoDepth(%q) = %q, want %q", in, got, want)
		}
	}
}

// Contract: _language_from_path first-suffix-match semantics, including paths
// with no mapped extension.
func TestLanguageFromPathGolden(t *testing.T) {
	paths := []string{
		"src/auth/login.py", "db/migrations/0001_init.sql", "web/App.tsx",
		"cmd/main.go", "config/settings.yml", "tests/test_login.py",
		"Dockerfile", "README.md", "script.unknownext",
	}
	want := []string{"python", "sql", "typescript", "go", "yaml", "python", "", "markdown", ""}
	for i, p := range paths {
		if got := languageFromPath(p); got != want[i] {
			t.Errorf("languageFromPath(%q) = %q, want %q", p, got, want[i])
		}
	}
}

// Contract: _extract_languages is the sorted unique set.
func TestExtractLanguagesGolden(t *testing.T) {
	want := []string{"go", "markdown", "python", "sql", "typescript", "yaml"}
	if got := extractLanguages(fixturePR()); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}

// Contract: _extract_areas emits areas in area_patterns declaration order;
// no hit falls back to ["application"].
func TestExtractAreasGolden(t *testing.T) {
	paths := []string{
		"src/auth/login.py", "db/migrations/0001_init.sql", "web/App.tsx",
		"cmd/main.go", "config/settings.yml", "tests/test_login.py",
		"Dockerfile", "README.md", "script.unknownext",
	}
	want := []string{"auth", "database", "frontend", "tests", "config", "infra"}
	if got := extractAreas(paths); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	if got := extractAreas(nil); !reflect.DeepEqual(got, []string{"application"}) {
		t.Fatalf("empty: got %v", got)
	}
	if got := extractAreas([]string{"lib/util.go"}); !reflect.DeepEqual(got, []string{"application"}) {
		t.Fatalf("plain: got %v", got)
	}
}

// Contract: _risk_signals ordering and triggers (auth/database areas, config
// suffixes, test paths; >=25 files trips the footprint signal).
func TestRiskSignalsGolden(t *testing.T) {
	pr := fixturePR()
	areas := extractAreas([]string{
		"src/auth/login.py", "db/migrations/0001_init.sql", "web/App.tsx",
		"cmd/main.go", "config/settings.yml", "tests/test_login.py",
		"Dockerfile", "README.md", "script.unknownext",
	})
	want := []string{
		"touches authentication or security-sensitive paths",
		"modifies data model or schema-affecting code",
		"includes configuration changes",
		"test behavior updated",
	}
	if got := riskSignals(pr, areas, len(pr.ChangedFiles)); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}

	// 25 plain .go files: only the footprint signal (Python golden).
	files := make([]schemas.ChangedFile, 25)
	for i := range files {
		files[i] = schemas.ChangedFile{Path: "pkg/modx/filex.go"}
	}
	big := schemas.GitHubPRData{Title: "big", ChangedFiles: files}
	bigAreas := extractAreas([]string{"pkg/modx/filex.go"})
	want = []string{"large change footprint across many files"}
	if got := riskSignals(big, bigAreas, 25); !reflect.DeepEqual(got, want) {
		t.Fatalf("big: got %v, want %v", got, want)
	}
}

// Contract: _ai_generated_confidence = marked-blobs / non-empty-blobs, capped;
// zero evidence -> 0.0.
func TestAIGeneratedConfidenceGolden(t *testing.T) {
	if got := aiGeneratedConfidence(fixturePR()); got != 0.2 { // 1 of 5 blobs
		t.Fatalf("got %v, want 0.2", got)
	}
	if got := aiGeneratedConfidence(schemas.GitHubPRData{}); got != 0.0 {
		t.Fatalf("empty: got %v, want 0.0", got)
	}
	all := schemas.GitHubPRData{Title: "Generated by Claude", Description: "chatgpt did this"}
	if got := aiGeneratedConfidence(all); got != 1.0 {
		t.Fatalf("all-marked: got %v, want 1.0", got)
	}
}

// Contract: _pr_summary strips the description; empty description falls back
// to "<title>. Files changed: <n>.".
func TestPrSummaryGolden(t *testing.T) {
	if got := prSummary(fixturePR()); got != "Implements OAuth2 login flow." {
		t.Fatalf("got %q", got)
	}
	pr := fixturePR()
	pr.Description = ""
	pr.Title = "T"
	if got := prSummary(pr); got != "T. Files changed: 9." {
		t.Fatalf("got %q", got)
	}
}

// Contract: _write_context_file creates <repo>/.pr-af-context/<name> with the
// exact content and returns its path.
func TestWriteContextFile(t *testing.T) {
	repo := t.TempDir()
	path, err := writeContextFile("hello context", "meta_semantic_context.json", repo)
	if err != nil {
		t.Fatal(err)
	}
	want := filepath.Join(repo, ".pr-af-context", "meta_semantic_context.json")
	if path != want {
		t.Fatalf("path = %q, want %q", path, want)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != "hello context" {
		t.Fatalf("content = %q", b)
	}
}

// Contract: _file_changes_from_metadata maps ChangedFile metadata onto
// FileChange stubs with empty hunks.
func TestFileChangesFromMetadata(t *testing.T) {
	got := fileChangesFromMetadata(fixturePR())
	if len(got) != 9 {
		t.Fatalf("len = %d", len(got))
	}
	first := got[0]
	if first.Path != "src/auth/login.py" || first.Language != "python" ||
		first.LinesAdded != 3 || first.LinesRemoved != 1 || len(first.Hunks) != 0 || first.Hunks == nil {
		t.Fatalf("got %+v", first)
	}
}

// Contract: filterPairs drops empty values and dedups keys (last value wins,
// first position kept) — dict-comprehension semantics.
func TestFilterPairs(t *testing.T) {
	in := []prompts.StrPair{
		{Key: "a", Val: "1"}, {Key: "b", Val: ""}, {Key: "c", Val: "3"}, {Key: "a", Val: "9"},
	}
	want := []prompts.StrPair{{Key: "a", Val: "9"}, {Key: "c", Val: "3"}}
	if got := filterPairs(in); !reflect.DeepEqual(got, want) {
		t.Fatalf("got %v, want %v", got, want)
	}
}
